#    ====================
#    Этот параметр указывает, следует ли использовать симулятор Gazebo для визуализации и тестирования манипулятора.
use_gazebo: false
#    Определяет тип входящих команд. "unitless" указывает, что команды не имеют единиц измерения (используется геймпад) и, возможно, должны быть отнормированы внутри системы.
command_in_type: "unitless"

#    ====================
#    Значения масштаба можно изменить для уменьшения или увеличения скорости движения. Меньшие значения приведут к более плавному и медленному движению.
#
#    linear: управление скоростью линейного движения манипулятора.
#    rotational: управление скоростью вращательного движения манипулятора.
#    joint: управление скоростью движения суставов манипулятора.
scale:
  linear: 0.8
  rotational: 1.0
  joint: 0.7
#    Увеличение этого параметра может привести к более плавному, но более медленному движению.
#    Период времени (в секундах) между публикациями состояния манипуятора. Значение 0.034 озночает, что обновления состояния отправляются примерно 29 раз в секунду.
publish_period: 0.034
#    Этот параметр можно установить в false для увеличения плавности за счет увеличения задержки.
low_latency_mode: false
#    Тип сообщения, используемого для отправки команд манипулятору. trajectory_msgs/JointTrajectory является стандартным типом сообщения ROS для отправки траекторий суставов.
command_out_type: trajectory_msgs/JointTrajectory

#    Указывает на то, что система должна публиковать положения суставов.
publish_joint_positions: true
#    Указывает на то, что система должна публиковать скорости суставов.
publish_joint_velocities: true
#    Указывает на то, что система не должна публиковать ускорения суставов.
publish_joint_accelerations: false

#    ====================
#    Имя плагина для сглаживания сигнала, в данном случае используется "ButterworthFilterPlugin" для онлайн-сглаживания.
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

#    ====================
is_primary_planning_scene_monitor: true
move_group_name: arm
#    Имя ЛСК, относительно которого планируются движения. 
planning_frame: Link_0
ee_frame_name: EE
robot_link_command_frame: Link_0

#    ====================
#    Время ожидания для входящих команд. Если команда не получена в течение 0.1 секунды, она может быть проигнорирована.
incoming_command_timeout: 0.1
#    Количество сообщений "остановки", которые должны быть опубликованы при прекращении команд.
num_outgoing_halt_msgs_to_publish: 4
#    Пороговое значение, ниже которого манипулятор может входить в область сингулярности, что опасно для управления.
lower_singularity_threshold: 60.0
#    Пороговое значение, при превышении которого манипулятор должен немедленно остановиться, чтобы избежать сингулярности.
hard_stop_singularity_threshold: 70.0
#    Запас значений степеней подвижности, который оставляет система, чтобы избежать достижения физических пределов суставов.
joint_limit_margin: 0.1
#    Множитель для порога выхода из области сингулярности.
leaving_singularity_threshold_multiplier: 2.0

#    ====================
#    Топик для входящих команд.
cartesian_command_in_topic: ~/delta_twist_cmds
#    Топик для входящих команд степеней подвижности.
joint_command_in_topic: ~/delta_joint_cmds
#    Топик для публикации значений степеней подвижности.
joint_topic: /joint_states
#    Топик для публикации статуса системы
status_topic: ~/status
#    Топик для отправки команд траектории суставов контроллеру.
command_out_topic: /manipulator_joint_trajectory_controller/joint_trajectory

#    Указывает, следует ли проверять столкновения.
check_collisions: false
#    ====================
#    Увеличение этого параметра может привести к более плавному движению, поскольку манипулятор будет более часто проверять на столкновения и корректировать свое движение соответственно (20 раз в секунду).
collision_check_rate: 20.0
#    ====================
self_collision_proximity_threshold: 0.01
scene_collision_proximity_threshold: 0.02
