# Default initial positions for bcn3d_moveo's ros2_control fake system

initial_positions:
  Gripper_Idol_Gear_Joint: 0
  Gripper_Servo_Gear_Joint: 0
  Joint_1: 0
  Joint_2: 0
  Joint_3: 0
  Joint_4: 0
  Joint_5: 0
  Pivot_Arm_Gripper_Idol_Joint: 0
  Pivot_Arm_Gripper_Servo_Joint: 0
  Tip_Gripper_Idol_Joint: 0
  Tip_Gripper_Servo_Joint: 0