# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - Gripper_Idol_Gear_Joint
      - Gripper_Servo_Gear_Joint
      - Tip_Gripper_Servo_Joint
      - Tip_Gripper_Idol_Joint
      - Pivot_Arm_Gripper_Idol_Joint
      - Pivot_Arm_Gripper_Servo_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity