# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    manipulator_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    servo_controller:
      type: joint_trajectory_controller/JointGroupPositionController

# parameters for each controller listed under controller manager
manipulator_joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
    state_publish_rate: 30.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

gripper_joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - Gripper_Idol_Gear_Joint
      - Gripper_Servo_Gear_Joint
      - Tip_Gripper_Servo_Joint
      - Tip_Gripper_Idol_Joint
      - Pivot_Arm_Gripper_Idol_Joint
      - Pivot_Arm_Gripper_Servo_Joint
    state_publish_rate: 30.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0